### PR TITLE
Feat/add fba pages limit

### PR DESCRIPTION
**Pull request by rafaelbreno**
Related to #1481 

Differences:
- Add `FACEBOOK_PAGES_LIMIT` environment variable into `settings_common.py`
- Add context to retrieve `FACEBOOK_PAGES_LIMIT` value
- Implement context value into _templates/channels/types/facebookapp/claim.haml_

### CODE REVIEW

**Comment by rowanseymour** [comment]
This doesn't feel like it should be a setting... if we can't make a quick fix just by adding `limit=100` then I think we should be doing this properly by fetching all pages of results.

**Comment by rafaelbreno** [comment]
@rowanseymour we've a account to manage the pages connections, so the total amount of manage pages vary, e.g at the moment this account manage approximately 137 pages, and with the time it can vary.

**Comment by rowanseymour** [comment]
What are you planning to set the limit to? if it works for you to set it to `200` or whatever, there's no downside to using that number for everyone. It doesn't need to be a setting. If it doesn't work... then we need to do proper paging.

**Comment by rafaelbreno** [comment]
#1495

**Pull request closed without merging**
