### PR TITLE
Perspective for NLP Dataset on RapidPro

### PR DESCRIPTION
**Pull request by matmsa27**

### CODE REVIEW

**Comment by nicpottier** [comment]
Hi @matmsa27, we ended up implementing this in: 
  https://github.com/nyaruka/rapidpro/pull/2550

We added Wit and Luis so that you could add BotHub. If you can open a PR on the Nyaruka repo with a BotHub type that would be super helpful.

Thanks!

**Comment by matmsa27** [comment]
Hi @nicpottier , thanks for remembering me. Ok, my priority now is it. I'll get the branch and create a BotHub type, and then open a PR. I'm glad about contributing. 

Regards. Thanks.

**Comment by nicpottier** [comment]
Hi @matmsa27 can you give us a quick status update on this? We are due to code freeze on Monday for 5.2 and would love to get BotHub support in.

**Comment by matmsa27** [comment]
Hi @nicpottier , the Bothub Classifier type it's almost ready. One detail is missing from bothub svg, tomorrow morning this will be changed and I will send the pr. My work is here in this `[branch](https://github.com/Ilhasoft/rapidpro/tree/feature/add_bothub_type)` if you want to check.

Thanks a lot for your attention.
Regards.

**Pull request closed without merging**
