### PR TITLE
add missing temba template tag library to templates/includes/nav.haml

### PR DESCRIPTION
**Pull request by tobiasmcnulty**
Fixes issue #358

### CODE REVIEW

**Comment by nicpottier** [comment]
woot.

**Comment by nicpottier** [comment]
Oh, can we get your autograph on:
  https://raw.githubusercontent.com/rapidpro/rapidpro/master/CONTRIBUTING.md

**Comment by tobiasmcnulty** [comment]
Emailed to you

**Comment by nicpottier** [comment]
Excellent, want to add yourself to:
  https://github.com/rapidpro/rapidpro/blob/master/CONTRIBUTORS.md

While you are at it? We'll merge afterwards.

**Pull request merged**
