### PR TITLE
Fixed misnamed dlr-url parameter on Jasmin channel

### LINKED ISSUE #680: Misnamed DLR URL parameter for Jasmin channel
The DLR URL parameter expected by Jasmin is actually called `dlr-url` instead of just `dlr`. I'll be sending a pull request for this soon.

https://github.com/rapidpro/rapidpro/blob/3ab9a8f2906fbca01c4154134e2e3a8487e2e1e2/temba/channels/types/jasmin/type.py#L51

### PR DESCRIPTION
**Pull request by idevsoftware**
Fixes #680

### CODE REVIEW

**Comment by norkans7** [comment]
Good catch, it seems we need to specify dlr as yes too. Can you add that too and a couple of asserts to test those 2 at https://github.com/rapidpro/rapidpro/blob/master/temba/channels/tests.py#L8219

**Comment by idevsoftware** [comment]
@norkans7 done, thanks!

**Comment by norkans7** [comment]
Looks good @idevsoftware, you can add yourself at the bottom of https://github.com/rapidpro/rapidpro/blob/master/CONTRIBUTORS.md
And we'll merge after the build passes

**Comment by norkans7** [comment]
Thanks @idevsoftware

**Comment by idevsoftware** [comment]
Thanks to you! I'd rather make some more substantial contributions before adding myself to the contributors file (which I hopefully will).

**Pull request merged**
