### PR TITLE
Update django.po

### PR DESCRIPTION
**Pull request by JesusEkie**
An improved translation to better reflect the original message.

### CODE REVIEW

**Comment by norkans7** [comment]
Hey @JesusEkie can you make the translation on Transifex?

https://www.transifex.com/rapidpro/rapidpro/

**Comment by JesusEkie** [comment]
Hey @norkans7 

After sleepless nights, translating RapidPro into French today, I received a message from Transifex stating that someone had downloaded an old version of the French translation file. All my translation work for RapidPro in French disappeared while I was about to fully translate all the fields.

You can check the activity of Transifex to confirm it. I really do not know why my translation was simply deleted.

**Comment by nicpottier** [comment]
Hi @JesusEkie, don't think anything has been lost. Just the contrary I've been playing with translations to make sure your work doesn't go to waste. There's a few issues I've been working to resolve:

1. The PO files themselves for RapidPro were far out of date from the real code. These files are generated by `makemessages` and that hadn't been run for years, so even a fully translated PO file would only affect some pages and a great things were missing.

2. The PO files on Transifex were also out of sync with the RapidPro ones, so we were doubly out of date.

3. The MO files which are actually used by Django to display translations were out of date because `compilemessages` wasn't run regularly.

I've addressed 2) by making sure Transifex is now integrated with Github so will always pull the latest PO files as they are updated.

I'm working on making 1) and 3) part of the build process so that builds fail if we have out of date PO or MO files to makes sure we don't fall behind as we have. I'm working on that here: 
   https://github.com/rapidpro/rapidpro/pull/925

I should be done with that today or tomorrow at the latest, at which time we should have updated PO and MO files and all translations you do should be valid and appropriate. I'm pretty sure we will still be able to merge in your PO file with Transifex and most of those translations will take at that time, but there will certainly be many that aren't translated because the PO file you were using was out of date.

I apologize for that and want to thank you for both taking on doing some translations and for motivating us to do better with these locale files and putting in a process that will guarantee these stay up to date in the future.

I'll update here when I have more.

**Comment by JesusEkie** [comment]
Thank you @nicpottier for you answer.
You guy owe me a cup of coffee :-)

While you are working on it can I proceed to U-Report?
I saw that the French version contains untranslated fields.

**Comment by nicpottier** [comment]
Ok, finally got that build working and updated `django.po` and `djangojs.po` (those will now be guaranteed to be updated when code changes, as will the `mo` files)

Merged to master and it looks like Transifex picked those up and merged them correctly. So I think if you do the translation there then once they are 100% reviewed Transifex will open a PR for them to be merged. 

Thanks!

Note that U-Report has the same problems as RapidPro (po files out of date, I'll try to do the same with the travis build and Transifex integration tomorrow)

**Pull request closed without merging**
