### PR TITLE
allow USSD flows to start someone else in a flow

### PR DESCRIPTION
**Pull request by smn**
rapidpro_-_visually_build_interactive_sms_applications

I've not tested this on a phone yet but this does expose the required functionality in the UI.

This addresses issue #429

### CODE REVIEW

**Comment by smn** [comment]
tests are failing due to migrations unrelated to this PR.

**Comment by nicpottier** [comment]
We'll have an upmerge to fix tests but will need a test for this functionality before we merge as well.

**Comment by smn** [comment]
@nicpottier happy to add a test. Could you provide some guidance at what level would you like this to be tested in a way that it currently isn't yet? The model level test I'm seeing relates to flows migrating to version 9 of the flow spec, other than that I'm not immediately seeing a test that I can use as a starting point.

**Comment by nicpottier** [comment]
Any of the FlowFileTests in /temba/flows/tests.py should be good examples. Test should start a USSD flow that starts a Messaging flow as an action.

**Comment by jpaidoussi** [comment]
@nicpottier @smn It looks like something I did made this PR's diff unreadable even though it should be a small change compared to the master branch. If you close this PR I will create a new one from our branch which should have the right diff.

**Comment by smn** [comment]
Yeah also confused, closing this PR. Please reference this one in the one you're creating?

**Pull request closed without merging**
