### PR TITLE
Lenght on "categorize as"

### PR DESCRIPTION
**Pull request by teehamaral**
This PR includes the limit on "categorize as" to 35 characters (#453).

### CODE REVIEW

**Comment by nicpottier** [comment]
@ericnewcomer plz review

**Comment by teehamaral** [comment]
Sometimes the users write more than 35 characters, so they think they're saving everything, but only 35 are saved. Adding this limit, we can avoid this problem.

**Comment by ericnewcomer** [comment]
Ha, Nic found where this value is indeed truncated to 36 characters when saving the flows. So it is indeed a RapidPro inconsistency. That said, these should be bumped to the real limit of 36.

**Comment by nicpottier** [comment]
Sweet, thanks guys!

**Comment by teehamaral** [comment]
🙂

**Pull request merged**
